name: Cypress Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  cypress-run:
    runs-on: ubuntu-latest

    steps:
    # Paso 1: Configurar el repositorio
    - name: Checkout code
      uses: actions/checkout@v2

    # Paso 2: Instalar Node.js
    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'  # Versión de Node.js que usarás

    # Paso 3: Instalar las dependencias del proyecto (incluyendo Cypress)
    - name: Install dependencies
      run: |
        npm install

    # Paso 4: Ejecutar los tests de Cypress
    - name: Run Cypress tests
      run: |
        npx cypress run
